// <auto-generated />
using System;
using EmployeeApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeApi.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    [Migration("20240407113416_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeApi.Infrastructure.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BossId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSalary")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BossId");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasFilter("[Role] = 'Ceo'");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSalary = 200000,
                            EmploymentDate = new DateTime(2010, 1, 1, 1, 1, 1, 0, DateTimeKind.Utc),
                            FirstName = "John",
                            HomeAddress = "123 Main St",
                            LastName = "Doe",
                            Role = "Ceo"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(1985, 5, 15, 1, 0, 0, 0, DateTimeKind.Utc),
                            BossId = 1,
                            CurrentSalary = 150000,
                            EmploymentDate = new DateTime(2012, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Jane",
                            HomeAddress = "456 Maple Ave",
                            LastName = "Smith",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1990, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            BossId = 2,
                            CurrentSalary = 100000,
                            EmploymentDate = new DateTime(2015, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Bob",
                            HomeAddress = "789 Elm St",
                            LastName = "Johnson",
                            Role = "Developer"
                        });
                });

            modelBuilder.Entity("EmployeeApi.Infrastructure.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeApi.Infrastructure.Entities.Employee", "Boss")
                        .WithMany()
                        .HasForeignKey("BossId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Boss");
                });
#pragma warning restore 612, 618
        }
    }
}
